
server:
  port: 8081
  servlet:
    encoding:
      charset: utf-8
      force: true
spring:
  datasource:
    hikari:
      maximum-pool-size: 20        # 계산된 16개보다 여유있게
      minimum-idle: 10             # 기본 유지할 최소 커넥션
      idle-timeout: 300000         # 5분
      connection-timeout: 30000    # 30초
      max-lifetime: 1200000        # 20분
    url: jdbc:h2:mem:test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      '[hibernate.default_batch_fetch_size]': 100
      '[hibernate.format_sql]': true
    show-sql: true
  output:
    ansi:
      enabled: always


logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    com.my.relink: DEBUG
    org.springframework.web.socket: DEBUG
    org.springframework.messaging: DEBUG

cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    s3:
      bucket: ${S3_BUCKET}
    region:
      static: ap-northeast-2
    stack:
      auto: false

jwt:
  secret:
    key: XyZ1a2b3c4d5e6f7g8h9i0j1k2l3m4n5o6p7q8r9s0t1u2v3w4x5y6z7A8B9C0D1

toss:
  widget-secret-key: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6 #결제 위젯 연동 api 테스트를 위한 공개키
  client-key: test_gck_docs_Ovk5rk1EwkEbP0W43n07xlzm #결제 위젯 연동 api 테스트를 위한 공개키