server:
  port: 9090
  servlet:
    encoding:
      charset: utf-8
      force: true
spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      '[hibernate.default_batch_fetch_size]': 100
      '[hibernate.format_sql]': true
    show-sql: true
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      max-file-size: 5MB

logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    com.my.relink: DEBUG
    org.springframework.web.socket: DEBUG
    org.springframework.messaging: DEBUG


jwt:
  secret:
    key: ${JWT_SECRET_KEY}


cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    s3:
      bucket: ${S3_BUCKET}
    region:
      static: ap-northeast-2
    stack:
      auto: false