name: PR Build Test

on:
  pull_request:
    branches:
      - main
      - dev

env:
  JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
  S3_BUCKET: ${{ secrets.S3_BUCKET }}
  S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
  S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
  ELASTIC_VERSION: ${{ secrets.ELASTIC_VERSION }}
  ELASTIC_PASSWORD: ${{ secrets.ELASTIC_PASSWORD }}
  LOGSTASH_INTERNAL_PASSWORD: ${{ secrets.LOGSTASH_INTERNAL_PASSWORD }}
  KIBANA_SYSTEM_PASSWORD: ${{ secrets.KIBANA_SYSTEM_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
        
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test 

      # - name: Run tests
        # run: ./gradlew test 
